### ISSUE TITLE
多次调用时,job或listener的run方法内如果使用ctx.service或其他自定义扩展,ctx.service有概率是undefined

### ISSUE THREAD

**Issue by mywei1989** [mywei1989/egg-bus#35]
快速且多次调用时,job或listener的run方法内如果使用ctx.service或其他自定义扩展,ctx.service有概率是undefined  
复现代码如下:
```
// app/controller/home.js
const { Controller } = require('egg');

class HomeController extends Controller {
  async index() {
    const { ctx } = this;
    for(let index=0;index<10;index++) {
      this.app.bus.dispatch('order', {'a':index}, {removeOnComplete: true})
    }
    ctx.body = 'hi, egg';
  }
}

module.exports = HomeController;

```
```
// app/jobs/order.js
const { Job } = require("egg-bus");
class OrderJob extends Job {
  static get queue() {
    return "queue_job_order"; // 使用的队列名称
  }
  static get attempts() {
    return 0; // 重试次数
  }

  async run(data, job) {
    try{
     // 这里会概率性报 TypeError: Cannot read properties of undefined (reading 'hkt') service 或 customLoad配置的都存在这个问题
      let res = await this.ctx.service.hkt.request('aaa',data) 
      console.log(res)
    } catch(e){
      console.log(e)
    }

  }

  failed(data) {
    // 当 job 失败并重试达到限定次数后调用
  }
}

module.exports = OrderJob;
```
```
// app/service/hkt.js
const Service = require('egg').Service
class HktService extends Service {
  async request(a, b){
    return {a,b}
  }
}
module.exports = HktService

```
有概率发生的完整报错如下:
```
TypeError: Cannot read properties of undefined (reading 'hkt')
    at OrderJob.run (F:\GitSource\temp\eggbustest\app\jobs\order.js:30:35)
    at Queue.<anonymous> (F:\GitSource\temp\eggbustest\node_modules\.pnpm\egg-bus@2.0.3_bull@4.16.0\node_modules\egg-bus\lib\bus.js:103:29)
    at handlers.<computed> (F:\GitSource\temp\eggbustest\node_modules\.pnpm\bull@4.16.0\node_modules\bull\lib\queue.js:733:42)
    at Queue.processJob (F:\GitSource\temp\eggbustest\node_modules\.pnpm\bull@4.16.0\node_modules\bull\lib\queue.js:1210:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mywei1989** [comment]
与本issue https://github.com/hexindai/egg-bus/issues/6 类似
只不过这里是egg标准的 service 而 那边是挂载在app 上的mysql 插件?

**Comment by seekcx** [comment]
抱歉，已经很多年没有使用egg，并且这个插件有些东西已经过时了，不建议继续使用，如果需要使用请尝试fork修复问题。

**Comment by mywei1989** [comment]
在job 或listener 中 如果使用了ctx上的对象甚至是 在配置文件中  customLoader 进app 中的模块
都可能无法被执行
原因可能是 job 或listener  中的ctx 是由 app.createAnonymousContext()创建的,而在创建时,这是的ctx可能是不完整的(比如缺少 serviceClasses) 从而导致 上诉问题.
目前还没找到解决方案

**Comment by mywei1989** [comment]
是eggjs 的问题
